doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    platform_service: App\Doctrine\Platform
    options:
      userDefinedFunctions:
        mb_strtolower:
          callback: mb_strtolower
          numArgs: 1
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    dql:
      string_functions:
        mb_strtolower: App\Doctrine\MbStrtolower
        in_array: App\Doctrine\InArray
