services:
    php-fpm:
        image: ghcr.io/bullshitsoftware/doxter-php-fpm:latest
        volumes:
            - db:/db
        environment:
            APP_SECRET: yourverysecretsecret
    nginx:
        image: ghcr.io/bullshitsoftware/doxter-nginx:latest
        environment:
            APP_SERVER_NAME: localhost
        ports:
            - "80:8080"
        depends_on:
            - php-fpm

volumes:
    db:
