services:
  php-fpm:
    image: ghcr.io/bullshitsoftware/doxter-php-fpm:latest
    user: 1000:1000
    volumes:
      - db:/db
    environment:
      APP_SECRET: yourverysecretsecret
  nginx:
    image: ghcr.io/bullshitsoftware/doxter-nginx:latest
    user: 1000:1000
    environment:
      APP_SERVER_NAME: localhost
      APP_ACCESS_LOG_FORMAT: |
        '$$remote_addr [$$http_x_real_ip] - $$remote_user [$$time_local]'
        '"$$request" $$status $$bytes_sent'
        '"$$http_referer" "$$http_user_agent" "$$gzip_ratio"'
    ports:
      - '80:8080'
    depends_on:
      - php-fpm

volumes:
  db:
