name: build

on:
    push:
        tags:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: buildx
              uses: docker/setup-buildx-action@v1
            - name: build base and dev images
              env:
                GITHUB_REF: ${{ github.ref }}
                USERNAME: ${{ github.actor }}
              run: |
                ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
                echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${USERNAME} --password-stdin
                docker buildx build --push -f build/php/Dockerfile \
                -t ghcr.io/${USERNAME}/doxter-php:${ref} -t ghcr.io/${USERNAME}/doxter-php:latest .
                docker buildx build --push -f build/devcontainer/Dockerfile \
                -t ghcr.io/${USERNAME}/doxter-devcontainer:${ref} -t ghcr.io/${USERNAME}/doxter-devcontainer:latest .
            
            - name: install front deps
              run: docker run -v $GITHUB_WORKSPACE:/app -w /app --rm --entrypoint npm node install
            - name: build front
              run: docker run -v $GITHUB_WORKSPACE:/app -w /app --rm --entrypoint npm node run build
            - name: install php deps
              run: docker run -v $GITHUB_WORKSPACE:/app -w /app -e APP_ENV=test --rm composer install
            
            - name: run tests
              run: |
                docker run -v $GITHUB_WORKSPACE:/app -w /app -e APP_ENV=test -u $(id -u $USER):$(id -g $USER) \
                ghcr.io/bullshitsoftware/doxter-devcontainer:latest make tests
            - name: remove php dev deps
              run: docker run -v $GITHUB_WORKSPACE:/app -w /app -e APP_ENV=prod --rm composer install --no-dev
            
            - name: build prod images
              env:
                GITHUB_REF: ${{ github.ref }}
                USERNAME: ${{ github.actor }}
              run: |
                ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
                echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${USERNAME} --password-stdin
                docker buildx build --push -f build/php-fpm/Dockerfile \
                -t ghcr.io/${USERNAME}/doxter-php-fpm:${ref} -t ghcr.io/${USERNAME}/doxter-php-fpm:latest .
                docker buildx build --push -f build/nginx/Dockerfile \
                -t ghcr.io/${USERNAME}/doxter-nginx:${ref} -t ghcr.io/${USERNAME}/doxter-nginx:latest .

