name: build

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/bullshitsoftware/doxter-devcontainer:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: pull dev image
        run: docker pull $IMAGE
      - name: install front deps
        run: |
          docker run -v $GITHUB_WORKSPACE:/app -w /app --rm --entrypoint npm -e HOME=/app \
          -u $(id -u $USER):$(id -g $USER) $IMAGE install
      - name: build front
        run: |
          docker run -v $GITHUB_WORKSPACE:/app -w /app --rm --entrypoint npm -e HOME=/app \
          -u $(id -u $USER):$(id -g $USER) $IMAGE run build
      - name: install php deps
        run: |
          docker run -v $GITHUB_WORKSPACE:/app -w /app --rm --entrypoint composer -e APP_ENV=prod \
          -u $(id -u $USER):$(id -g $USER) $IMAGE install --no-dev

      - name: buildx
        uses: docker/setup-buildx-action@v1
      - name: build images
        env:
          GITHUB_REF: ${{ github.ref }}
          USERNAME: ${{ github.actor }}
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d '/' -f3)"
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${USERNAME} --password-stdin
          docker buildx build --push -f build/php-fpm/Dockerfile \
          -t ghcr.io/${USERNAME}/doxter-php-fpm:${ref} -t ghcr.io/${USERNAME}/doxter-php-fpm:latest .
          docker buildx build --push -f build/nginx/Dockerfile \
          -t ghcr.io/${USERNAME}/doxter-nginx:${ref} -t ghcr.io/${USERNAME}/doxter-nginx:latest .
